flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
article:
  top_page:
    per: 20
    truncate: 200
question:
  top_page:
    per: 20
    truncate: 200
paginate:
  default: 10
time_format:
  full_time: "YYYY-MM-DD HH:mm"
  hour_time: "HH:mm"
search:
  per_page:
    default: 8
carrierwave:
 fog_cache_control: 1.hour
 fog_expiration: 1.hour
 fog_public: true
per_page:
  default: 10
